name: Build documentation and pack
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    if: |
      github.event_name != 'release' ||
      (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/'))
    name: Generate pack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - name: Install packages
        shell: bash
        run: |
          sudo pip install LinkChecker

      - name: Install doxygen 1.9.2
        shell: bash
        run: |
          wget -O doxygen.tgz https://sourceforge.net/projects/doxygen/files/rel-1.9.2/doxygen-1.9.2.linux.bin.tar.gz/download
          sudo tar -C /opt -xf doxygen.tgz
          sudo ln -s /opt/doxygen-1.9.2/bin/doxygen /usr/local/bin/
          which doxygen
          doxygen --version

      - name: Generate doxygen
        shell: bash
        run: |
          echo "::add-matcher::.github/doxygen.json"
          ./doxygen/gen_doc.sh
          echo "::remove-matcher owner=doxygen::"

      - name: Run linkchecker
        shell: bash
        run: |
          echo "::add-matcher::.github/linkchecker.json"
          ./doxygen/check_links.sh
          echo "::remove-matcher owner=linkchecker::"

      - name: Archive documentation
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./documentation
          retention-days: 1
          if-no-files-found: error

      - name: Archive documentation
        if: (github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        shell: bash
        run: |
          tar -cvjf /tmp/doc.tbz2 -C ./documentation .

      - uses: actions/checkout@v3
        if: (github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        with:
          ref: gh-pages

      - name: Publish documentation
        if: (github.event_name == 'release' || github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        shell: bash
        run: |
          rm -rf ${GITHUB_REF_NAME}
          mkdir -p ${GITHUB_REF_NAME}
          tar -xvjf /tmp/doc.tbz2 -C ${GITHUB_REF_NAME}
          if ${{ github.event_name == 'release' }}; then
            rm -f latest
            ln -s ${GITHUB_REF_NAME} latest
            MSG="release"
          else
            MSG="branch"
          fi
          ./update_versions.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update documentation for ${MSG} ${GITHUB_REF_NAME}"
          git push
